point_table:
  p1:
    x: 0
    y: 0
  p2:
    x: 0
    y: 2000
  p3:
    x: 3000
    y: 2000
  p4:
    x: 3000
    y: 0
  p5:
    x: 0
    y: 0
  
  # On ajoute ici directement le dernir point manquant